remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: Bruno Braga
description: Tech Entrepreneur and Senior Software Engineer | Former CTO at Vest Social, Inc.
logo: /assets/img/profile.jpg
show_downloads: false

github:
  is_project_page: false
  owner_url: https://github.com/bragabruno
  owner_name: Bruno Braga
